import type { Store } from "./types";
import { TODAY } from "./rules";

/** 演示数据：覆盖 已充填冻结(带修订链) / 封药 / 未测长 三种闭环状态 */
export function seedStore(): Store {
  return {
    savedAt: TODAY,
    teeth: [
      {
        id: "#11",
        diagnosis: "外伤后变色 · 慢性根尖周炎",
        version: 2,
        updatedAt: "2026-09-12",
        canals: [
          {
            id: "#11-1",
            name: "1",
            lengthHistory: [
              { value: 22.0, at: "2026-09-05" },
              { value: 20.5, at: "2026-09-08", reason: "参考点改为切端，锉尖实测复测缩短 1.5mm" },
            ],
            masterApicalFile: "#35",
            medCount: 1,
            wetHistory: [false],
            nextVisit: "",
            nextVisitDate: "",
            filled: true,
            filledAt: "2026-09-12",
          },
        ],
      },
      {
        id: "#36",
        diagnosis: "慢性根尖周炎",
        version: 1,
        updatedAt: "2026-09-15",
        canals: [
          {
            id: "#36-MB",
            name: "MB",
            lengthHistory: [{ value: 19.5, at: "2026-09-12" }],
            masterApicalFile: "#30",
            medCount: 2,
            wetHistory: [true, true],
            nextVisit: "microscope",
            nextVisitDate: "2026-09-26",
            filled: false,
            filledAt: "",
          },
          {
            id: "#36-ML",
            name: "ML",
            lengthHistory: [{ value: 19.0, at: "2026-09-12" }],
            masterApicalFile: "#30",
            medCount: 2,
            wetHistory: [true, false],
            nextVisit: "dressing",
            nextVisitDate: "2026-09-26",
            filled: false,
            filledAt: "",
          },
          {
            id: "#36-D",
            name: "D",
            lengthHistory: [{ value: 21.0, at: "2026-09-12" }],
            masterApicalFile: "#35",
            medCount: 1,
            wetHistory: [false],
            nextVisit: "obturation",
            nextVisitDate: "2026-09-26",
            filled: false,
            filledAt: "",
          },
        ],
      },
      {
        id: "#46",
        diagnosis: "急性牙髓炎",
        version: 1,
        updatedAt: TODAY,
        canals: [
          {
            id: "#46-MB",
            name: "MB",
            lengthHistory: [{ value: 20.0, at: "2026-09-18" }],
            masterApicalFile: "#25",
            medCount: 0,
            wetHistory: [],
            nextVisit: "",
            nextVisitDate: "",
            filled: false,
            filledAt: "",
          },
          {
            id: "#46-ML",
            name: "ML",
            lengthHistory: [{ value: 19.5, at: "2026-09-18" }],
            masterApicalFile: "#25",
            medCount: 0,
            wetHistory: [],
            nextVisit: "",
            nextVisitDate: "",
            filled: false,
            filledAt: "",
          },
          {
            id: "#46-D",
            name: "D",
            lengthHistory: [],
            masterApicalFile: "",
            medCount: 0,
            wetHistory: [],
            nextVisit: "",
            nextVisitDate: "",
            filled: false,
            filledAt: "",
          },
        ],
      },
    ],
    revisions: [
      {
        id: "rv-seed-1",
        at: "2026-09-12",
        toothId: "#11",
        canalId: "#11-1",
        canalName: "1",
        field: "主尖锉号",
        oldValue: "#30",
        newValue: "#35",
        reason: "根尖孔粗大，试尖后确认主尖锉上调一号（术后复核修订）",
        versionBefore: 1,
        versionAfter: 2,
        snapshot: {
          id: "#11-1",
          name: "1",
          lengthHistory: [
            { value: 22.0, at: "2026-09-05" },
            { value: 20.5, at: "2026-09-08", reason: "参考点改为切端，锉尖实测复测缩短 1.5mm" },
          ],
          masterApicalFile: "#30",
          medCount: 1,
          wetHistory: [false],
          nextVisit: "",
          nextVisitDate: "",
          filled: true,
          filledAt: "2026-09-12",
        },
      },
    ],
    conflicts: [
      {
        id: "cf-seed-1",
        at: "2026-09-15",
        toothId: "#36",
        canalName: "MB",
        field: "充填",
        oldValue: "未充填",
        newValue: "充填",
        rule: "R3",
        ruleLabel: "R3 连续两次未干燥",
        message: "MB 已连续封药两次仍未干燥，充填被拦截，改约显微会诊（2026-09-26）。",
        action: "blocked",
      },
    ],
  };
}
